### ISSUE TITLE
mcyeti doesn't like to launch for whatever reason

### ISSUE THREAD

**Issue by cornfields74** [MESYETI/MCYeti#25]
![image](https://github.com/yeti0904/MCYeti/assets/131550775/1961e45f-03b4-4da1-b5c7-d5e1c3fa3137)
why

**Comment by MESYETI** [comment]
you have a file called worlds that you need to delete

**Comment by cornfields74** [comment]
what fucking file
![image](https://github.com/yeti0904/MCYeti/assets/131550775/2c6fc4d1-a32d-47d7-a1e0-8d6ed094c565)

**Comment by MESYETI** [comment]
inch resting

**Comment by MESYETI** [comment]
closing this because im working on a rewrite
